<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HarishGarg" ignored="0" name="Learning assertions" tests="1" failures="1" timestamp="05 Jun 2019 02:09:38 GMT" time="0.034" errors="0">
  <testcase name="asserttest" time="0.012" classname="testcases.assertion">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [xyz] but found [abc]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [xyz] but found [abc]
	at testcases.assertion.asserttest(assertion.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- asserttest -->
</testsuite> <!-- Learning assertions -->
